FROM apache/airflow:3.1.8

USER root

RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get clean

USER airflow

COPY requirements_airflow.txt .
RUN pip install --no-cache-dir -r requirements_airflow.txt
